apiVersion: v1
kind: Service
metadata:
  labels:
    run: airflow-sync
  name: airflow-sync
  namespace: dev
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: airflow-sync
  sessionAffinity: None
